version = 0.1
[default.deploy.parameters]
stack_name = "es03j"
resolve_s3 = true
s3_prefix = "es03j"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
