version = 0.1
[default.deploy.parameters]
stack_name = "java-maven-example01-sam"
resolve_s3 = true
s3_prefix = "java-maven-example01-sam"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
